### ISSUE TITLE
Compile and upload without errors but won't run

### ISSUE THREAD

**Issue by dmeylman** [tobozo/Rotatey_Balls#1]
I was able to compile and upload but there is no display. Using Lolin32 and OLED .96 display. Both tested working with other sketch. Please help. I'm pretty new to this. Thanks

**Comment by tobozo** [comment]
An empty screen means the MPU wasn't detected or the I2C bus is on different pins.

You can [set debug to true](https://github.com/tobozo/Rotatey_Balls/blob/master/Rotatey_Balls.ino#L13) for more verbose output.

If after a few seconds you get serial output, the MPU is fine, then check for the SDA/SCL pins on your LoLin32 documentation, then try to replace these values: 

    int sdaPin = 21;
    int sclPin = 22;

Or eventually try this:

    int sdaPin = SDA;
    int sclPin = SCL;

to see if it still compiles without error

**Comment by dmeylman** [comment]
I have tried the above and still no display.  Serial monitor output, WHO_AM_I error. Any idea what the error about. Thanks

**Comment by tobozo** [comment]
it's looking for a MPU6050 and can't find it

if you want to try without MPU maybe comment out lines 164, 165, 168 and 186 so it won't hang, I have no idea how the app will behave though

**Comment by dmeylman** [comment]
I'll try it. Thanks again for helping and very quick response...

**Comment by dmeylman** [comment]
It works...
![20180320_171849](https://user-images.githubusercontent.com/32586435/37690229-ecd5a58e-2c66-11e8-86f9-467c56fd206e.jpg)
